### ISSUE TITLE
missing jira module

### ISSUE THREAD

**Issue by knoxor** [woutervb/mattermost-jira-info#2]
Hi,
I'd like to integrate your plugin with mattermost and have followed the instructions. I'm trying to run the runme.py script but it's failing with error 

`Traceback (most recent call last):
  File "./runme.py", line 8, in <module>
    import hook
  File "/home/jenkins/mattermost-jira-info/hook.py", line 5, in <module>
    import jira
ImportError: No module named jira
`

I have copied the settings.example.py to settings.py and filled in the details.
I'm not familiar with python so any pointers would be appreciated.

thanks

**Comment by woutervb** [comment]
Hi knoxor, you missed the step in the readme that instructs to run pip -r requirements.txt
This should install the required python dependencies.
