### ISSUE TITLE
how to run rest requests through a proxy?

### ISSUE THREAD

**Issue by goeland86** [woutervb/mattermost-jira-info#3]
How would I configure the webhook server to run through a proxy to reach Jira?

Our Jira is hosted outside the intranet where we're setting up mattermost, and Mattermost is behind a proxy. How would I configure the settings to go through the proxy I need?

Thanks

**Comment by woutervb** [comment]
Based on the provided details I suggest that you run this daemon somewhere near the mattermost installation. Make sure that it can reach your Jira instance and that mattermost can reach this daemon on port 5000. The connections will be initiated by mattermost and have no relation to proxy.

**Comment by goeland86** [comment]
Hi Wouter,
Unfortunately in our case this isn't possible - we can run the daemon on the same machine as mattermost - but it needs to go through a proxy to get to our Jira instance, and that's what I need help configuring. We cannot run the daemon on a public machine due to security limitations imposed on us by the production sysadmin team.

I was wondering if there is a flag I'm missing somewhere that needs to be set in the configuration to use an http/https proxy when the daemon makes a request to the jira instance.

Thank you for your understanding.

**Comment by woutervb** [comment]
I did not get this from your question. But I now understand that you need the daemon to use an outgoing proxy to reach the jira installation.

I did some quick research, which resulted in the fact that `urllib3` does support proxies, which is used upstream by the `requests` module, and requests is used by the `jira` module that I used for this daemon.

And from the requests documentation I can find that if the environment variables HTTP_PROXY & HTTPS_PROXY are set, these will be used. See http://docs.python-requests.org/en/master/user/advanced/#proxies

So you might want to try to set the above environment variables before starting this daemon.

**Comment by goeland86** [comment]
Thanks, it can now access the outside world!
